### ISSUE TITLE
devcontainer fails to install nvidia-cublas-cu11

### ISSUE THREAD

**Issue by danbraunai** [alan-cooney/CircuitsVis#19]
When building the dev container locally (Mac M1), I get:
```
  RuntimeError

  Unable to find installation candidates for nvidia-cuda-nvrtc-cu11 (11.7.99)

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chooser.py:103 in choose_for
       99│ 
      100│             links.append(link)
      101│ 
      102│         if not links:
    → 103│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      104│ 
      105│         # Get the best link
      106│         chosen = max(links, key=lambda link: self._sort_key(package, link))
      107│ 

  • Installing nvidia-cuda-runtime-cu11 (11.7.99): Failed
```

I'm guessing the build works on the github codespace servers with GPUs, but it would be nice not to require a GPU to build.

**Comment by alan-cooney** [comment]
This is a PyTorch bug unfortunately - they have a fix at https://github.com/pytorch/pytorch/pull/89924/files but it hasn't been merged yet (essentially 1.13 doesn't specify the correct markers). For now a change to the lockfile should fix this - so I'll merge that in
