### ISSUE TITLE
Understanding the attention pattern visualization

### ISSUE THREAD

**Issue by nikipi** [alan-cooney/CircuitsVis#56]
Hey I am trying to understanding the attention pattern visualization, is the destination axis input text pass to encoder and source axis for decoder?

**Comment by alan-cooney** [comment]
Hi @nikipi - the terminology comes from https://transformer-circuits.pub/2021/framework/index.html 

![image](https://user-images.githubusercontent.com/41682961/232883679-995d7bf7-9ba7-4c9b-b43c-d5a1d83d7ece.png)

Let's say we have a tokenised phrase "The| person| was| walk|ing| the| dog". In this case an attention head could look at the destination token " the" and reasonably attend most to " walk" (as a source token) to get " dog" (the output token). If that's right, it would give a high attention value for that combination, and lower values for the destination token " the" with all other tokens before it.

A language model in practice outputs output tokens for every destination token, on every forward pass. This is why you get an attention matrix - for a single forward pass with that example prompt, it's predicting the next token for every token in that prompt (e.g. it'll predict something after " person" even though we already know " was" comes next).

I hope that helps and sorry I missed this earlier. If it's easier to chat about this just tag me and we can have a quick call
